// SPDX-License-Identifier: GPL-2.0
/* Converted from tools/testing/selftests/bpf/verifier/and.c */

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

struct trace_event_raw_sys_enter {
	short unsigned int type;
	unsigned char flags;
	unsigned char preempt_count;
	int pid;
	int __syscall_nr;
	long unsigned int args[6];
	char __data[0];
};

SEC("tracepoint/syscalls/sys_enter_execve")
int unreachable_arsh(struct trace_event_raw_sys_enter *ctx)
{
	/* simplified version of generated bytecode of bpf_wireguard.o */
	asm volatile("call 0x7\n\t"
		     "w1 = w0\n\t"
		     "w1 s>>= 31\n\t" /* -1 or 0*/
		     "w1 &= -134\n\t" /* -134 or 0 */
		     "if w1 s> -1 goto +2\n\t" /* non-taken, -134 only*/
		     "if w1 != 0xffffff78 goto +1\n\t" /* must take */
		     "r1 = r2\n\t" /* read not okay */);

	return 0;
}
char _license[] SEC("license") = "GPL";
